#!/bin/bash
#不同的项目有不同的路径
array[0]='backup'
#项目的主干目录是相同的
RELEASE="/data/"
 
for path in ${array[@]};
do
 #拼接文件路径
 releasepath=${RELEASE}${path}
 cd $releasepath
 #判断是否存在该目录
 if [ $? -eq 0 ];
 then
  echo $releasepath   #显示要操作的当前目录
  echo "Contains file:"
  #输出所有的内容
  echo *
  num=`ls -l | grep '^-' | wc -l`;
  #判断文件的数量是否超过5个（我只想保留最新的5个文件夹）
  if [$num -gt 5 ];
  then
   #计算超过5个多少
   num=`expr $num - 5`
   clean=`ls -tr | head -$num | xargs`
   echo "will delete file:"
   echo ${clean}
   #-n1 每次处理1个文件
   ls -tr | head -$num | xargs -i -n1 rm -rf {}
  fi
 fi
done
